services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-musiq}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-musiq}
      POSTGRES_DB: ${POSTGRES_DB:-musiq}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
